//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int ID { get; set; }
        public string NameAnimals { get; set; }
        public double Daily { get; set; }
        public Nullable<int> IDContinent { get; set; }
        public Nullable<int> IDFamalyAnimals { get; set; }
        public Nullable<int> IDRoom { get; set; }
        public Nullable<int> IDAnimalsHome { get; set; }
    
        public virtual Continent Continent { get; set; }
        public virtual AnimalsHome AnimalsHome { get; set; }
        public virtual FamelyAnimals FamelyAnimals { get; set; }
        public virtual Room Room { get; set; }
    }
}
